"""Comment on vote

Revision ID: 580ca7ba7446
Revises: 502b8a4d00e4
Create Date: 2014-12-07 12:46:45.784543

"""

# revision identifiers, used by Alembic.
revision = '580ca7ba7446'
down_revision = '502b8a4d00e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('comment', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'comment')
    ### end Alembic commands ###
