"""empty message

Revision ID: ed19f02bb1e
Revises: 2758f36a2fb5
Create Date: 2014-03-11 10:07:42.948881

"""

# revision identifiers, used by Alembic.
revision = 'ed19f02bb1e'
down_revision = '2758f36a2fb5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('preferred_language', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'preferred_language')
    ### end Alembic commands ###
